# Generated by Django 4.1.4 on 2022-12-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Make',
        ),
    ]
