# Generated by Django 4.1.4 on 2023-01-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='status',
            field=models.CharField(blank=True, default='RUN', max_length=200),
        ),
    ]
