# Generated by Django 4.1.4 on 2023-01-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_make_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Make',
        ),
    ]
