# Generated by Django 4.1.4 on 2023-01-04 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_delete_make'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targer', models.CharField(blank=True, max_length=200)),
                ('finish', models.CharField(blank=True, default='0', max_length=200)),
                ('status', models.CharField(blank=True, default='RUN', max_length=200)),
                ('shift', models.CharField(choices=[('MS', 'MS'), ('AS', 'AS'), ('NS', 'NS'), ('ALL', 'ALL')], default='MS', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.line')),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
