# Generated by Django 4.1.4 on 2023-03-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='staff',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
