# Generated by Django 4.1.4 on 2023-03-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_make_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='staff',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
