# Generated by Django 4.1.4 on 2023-06-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_make_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='box',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='pac',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='targer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
