# Generated by Django 4.1.4 on 2023-06-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_box_product_pac_product_targer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('key_QR',)},
        ),
    ]
