# Generated by Django 4.1.4 on 2023-06-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=200)),
                ('key_QR', models.CharField(blank=True, max_length=200)),
                ('line', models.CharField(blank=True, max_length=200)),
                ('pic', models.CharField(blank=True, max_length=200)),
                ('targer', models.CharField(blank=True, max_length=200)),
                ('finish', models.CharField(blank=True, default='0', max_length=200)),
                ('status', models.CharField(blank=True, default='RUN', max_length=200)),
                ('shift', models.CharField(choices=[('MS', 'MS'), ('AS', 'AS'), ('NS', 'NS'), ('ALL', 'ALL')], default='MS', max_length=200)),
                ('staff', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
